script:
- echo "hello world"
- echo $APP_KEY $APP_TOKEN

# Docker Build the Image
- docker build --target test --tag todo-app:test .

# Docker Run to Execute Test Package
- docker run -e APP_KEY -e APP_TOKEN -e board_id -e list_id_Done -e list_id_Pending -e list_id_ToDo todo-app:test Test

env:
  global:
    - APP_KEY=bb61abc465f91ddcefe71b425ff32869 
    - APP_TOKEN=cb7c2516b552d93d890d7517775620bb9f9ef43b9cf93ed595ba420fd1e3ce56
    - board_id=5ef1186ddea5ff1b03e085e6
    - list_id_ToDo=5ef1186d26a8d939ea575069
    - list_id_Pending=5ef1186d2fd57d026f03add0
    - list_id_Done=5ef1186dcbda554f16c6d66f

