services:
  - docker

script:
# Docker Build the Test Images
- docker build --target test --tag todo-app:test .

# Docker Run to Execute Unit Test Package
- echo "Running Unit Tests"
- docker run -e board_id -e list_id_Done -e list_id_Pending -e list_id_ToDo -e MONGO_LOGIN -e MONGO_PASS todo-app:test Test/view_model_test.py

# Docker Run to Execute Unit Integration Package - failed
#- echo "Running Integration Tests"
#- docker run -e board_id -e list_id_Done -e list_id_Pending -e list_id_ToDo -e MONGO_LOGIN -e MONGO_PASS todo-app:test Test/client_test.py

# Docker Run to Execute Unit E2E Selenium Package
# - echo "Running E2E Tests"
# comment out selenium test for module 10 for now due to failure
#
# - docker run -e board_id -e list_id_Done -e list_id_Pending -e list_id_ToDo -e MONGO_LOGIN -e MONGO_PASS todo-app:test Test/selenium_test.py
- echo "All Tests Have Been Completed"

# DockerHubLogin
- docker login --username "$docker_login" --password "$docker_pass"

# Docker Build the Prod and DockerPush
- docker build --target production --tag todo-app:prod .
- docker tag todo-app:prod legendarypan/todo-app:prod
- docker push legendarypan/todo-app:prod

# Pre-deploy Install
- curl -sS https://cli-assets.heroku.com/install.sh | sh
# - heroku update
# - heroku plugins:install @heroku-cli/plugin-container-registry


# using heroku credentials
# NOTES use auth token instead of API key and move to environment variable like docker_login 
- docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
- docker tag legendarypan/todo-app:prod registry.heroku.com/fengs-todo-app/web
- docker push registry.heroku.com/fengs-todo-app/web

# Trying diff deploy method
deploy:
  provider: script
  script: heroku container:release web --app fengs-todo-app
  # heroku container:push web --app fengs-todo-app
  on:
  #  all_branches: true
  #  branch: module_8
     branch: master # (revert back to this after merging module_9)
  #  branch: module_9

env:
  global:
    - SECRET_KEY=secret-key
    - board_id=5ef1186ddea5ff1b03e085e6
    - list_id_ToDo=5ef1186d26a8d939ea575069
    - list_id_Pending=5ef1186d2fd57d026f03add0
    - list_id_Done=5ef1186dcbda554f16c6d66f

# heroku_login heroku_pass heroku_api
# Trello API    
    - secure: i5EQkYyEcUnR/G5hONMVx4JkdEUFGb2FLSVr8u/MvWXdIgmfdeiLeLJKwqeF+J1ojsjsnBkBO2DXI//7mdSVDcRPkAaTbeLJLvT22bK4wZFjl6qxrq4j8U04sHxXR/IPbTFj5nefDybVDLaaqATFcqn3GTb0fBwUVNMchEo2IXl9/tkM+YLGfKhVpg9R1CDVRK7eoMbYAzgxzP1Do1udsuS8YE4+ajivG5ZiZC07/NDzJaADf+ArHNZ++r2LuA0bCvMjYe4GgHy7b3LM9hiPmXEyMT5u59KUp439g5O2hhEvlBxfU+meOgryFJLyoZAdCS3PTzJR7gCQLg/Lxnm6SnIL1wpxz1CP1Fmpb/z+toCDSVW5X1PT6/Ak9COEAjdBZD0DbsNf/HKX6I4YmdlP/el0Dp3gOUmHnv6NhT14BKznVNODu3NeDr6HzE7m3V+CaZ/Mp2oG6S1nbFQLQaw9/U8uHottONd0f432mYlS3kHhh/wxq4vc6cb0ZJT+fYHz2erUnjsMvqNFsd7CDEZnx8N56FiA4IVxLKy6/kCvwydxDQMg8+0KWEd5SdMETrALPbK26YKg8ySMK0fhfNmwSz4k7sRKsGyRrQo2LJuPe4OXPxzqADyuGCv1JNK4YiU3ZlbdYBVA1Eo5CkHk5sYcLgQiNAuWaPUNpVhm74p0uEQ=
    - secure: 5wo/rbXNuxaBr0uW799Qjl+XsrHvvaEvJ4lBrtE2ccPs5s6+8se42tT1rycwtbIcAROR00ZJy6B1ssnehns91prgIxv83QV1Tign+xStThO8GDfP8ofSlhUXXP9UWH4gUFYj1o3o7y1SQ7C+L+TptLXQOBYbJln/OYQYocE9CPriVAO9HCk9W578XNyoOt9SZzIpLHS6zN7GQv0ML/57kXRTEZBGj+T/EBonIvRbqwT6rJpsVCHt/O6knDi1ZuFFU3+cfSlZmFlQshfcBAn6vVLLPu9//Jnm3DGpikjCS6sXaP21DzlxcG+/ghR0DiUbvvVZeCfzxjPkLkNyMdNcHsr4DPBJU0oE05jcPDZ+Bw1VSuFUtUprivaAV3i8neafKtq92RutobyMerRIV8F5IHt968qWZ62nnJuFdcYhy5yWfJwaAcARJZPax6gm7jCRNL2s2St+t6aPrazRMZd4GSXxCNxFK795cFy+aU2UNdUPV93cpRtkrAT2Yx8nA5DLwVTZWgebGRgIJsJ5LqUbj9H6K5C9jeSKL5fLuKLZRcCa9lDM46t5zG3DqtzoaXZuQ/jhnCjRXue0otNdf+7Y9dQj7ic20n8J87OcQziqLBe1aQPs4RQfZpP5F8SfnH1iN1H6R9lhtjY20Rp6sypZoWffkZtuz2UB4uh/+4qInEY=
# docker login
    - secure: 7O6eN0xAm6elfanc+IDgn809IpeSG/NTgjQCTPkVl73yEZmk1bNOdSlqlV/WgIcvXrBe3bkY3zA4H6qTjtbVGDRrGKlVPLbb2kAdU1Rvx9TALa2iXiNCwX3DBxbdtEMhCbaUiaPAgRabNNxJZ9n94ltf/X6nV5Z27rn3d1QRM63mIS5oEjbwvNKplT2xtDxBIcP3MkHOwEB2k92pZLtmvM+EZbZU+LYd0AGg82sITZX6sewHsMb1m06eNLqXZzBFuGxTtnGwpO5SIXFI6PwlkbZp86GHjNMUvVTmwRxB3mDKQRar2Gx5PpgUH4NWjridBG/sL8ZInkjRa9C+issz5zd0/NRLQ5TgCETYdYnFuTWrJSTGCjgxQlcgylulqclWQ9zK6NXPDLku9+o8ypOHUm7XxC03wOaFfq2m0ilnrftPuTzBc0vGmCvD0ArIoTNDIbs8N/SM/Ma2uoodGy830YNEbka0uOuYS0NgO2Hh33LgWUh7rKYE1hcSRL+lY9OzNmEPM8JkxdfxqAA3SoSchj0UinS5LsrL0tYBXDxxgY0u1uzpm8Bp4p+SL5y5nrr4kS0br23IWS3z/tw+SwgBmX7Dk5Sac1SSoLyo6FLHGzJJOp1Cpz+bCCqLfoBMo8SOZvyHmvuw1HNEncnuQuyOnBEOaUj3dC/Do717v6TjNmY=
    - secure: JiKGdvaPsYEh0WrRcEdEUD5+8PFlglqMXe2qFJv5SeyPLeshcuDRcd7bWF3MLoQxCRxuFcGrvC+4CHJAbv1f3+BtNfRAs661h1kmVOBsfO2E3e8pwqGEwhfAdKJG5cAzL4MMa9Y2j+5YSImZE8OMCPxfhsUK7/ByPNFdgpcRsCqDHbOjFZlAUWCxAmDeOkSG3fsQ24nk/tmtHmeQ7JVd0cJaFF6ZEc0Ur4P/v2SqSm7VVl2pmNTOd+ItrHMmGRiTExGQ/ICw/60YLwglyLDiY05tlnNKBbVEhEdqMezWQTEv65rzjtcl7iR16a3IW//bRdW8qJOECzswzDYXsr50UwBq1vY/vsg28VPkROJTdbyKvdR3JyrMzUaSaK5n+zENWgPd7aFgcJSfUbRknEydaBt5mQv3/8NrUSraBIonqK4RWD//nUx6hv7MNiLR1gHvaL0mqPn5YnrxsFx3NLc8QsgkHXVclGNhuGKZB97tiZXuN+Ik1QUyKZsxpHggn4qBLztdOVVXV2DDf3lfDxpx95PUVh4QGCTxHBVv+J5yjtit5k3jqARqwWUDo8AK3tvRuQR7Bn6rFfoZBxS2n2IojbeGhFeMFkJKmhbDn5wVKaRRCrJkTLKH0luu1m2/0gjSWtVCYBzB6wtzwuF/IqDeJewtcsWy+GQxp0rPKKAlSEI=
# new heroku api HEROKU_API_KEY & HEROKU_LOGIN
    - secure: kOoEfyx8Q20qAL7A4RSR4HmXGYFdsRZw877vMnZBq+oGJbWS5q70461XzjVbz4Gv50IgK6yW0tmcHVO0QJAeg4DBXFxBIoBnair6sKlCr8SoYbmin4WYZjtxdciSlD/134WoQDEyoczjr1dUx093CqELw/lnzi4hmRL1oX2JPDM16SRXwZuF+ZC23kBEmfvlD1vlqnFIybJNva4kNRzw/sN89/eZBdadL9fu1jbFv8mvrKDukrTgJ3omJwykM8UurDYFz+gGtiJc7OF75CSfKFZNcrn9WFwFWfGESlgTL2SE9ptTc9Ce09Bntp+GhhH6DOQudEnQF2zwU2TBTdJg2zbcj5jwEqvyXElxXzIfzChYZugnwzveM9N58cEOO6BNkniSsHTb8+kGD5cWIFTGbmIouJXo/9DO5gJQ4hjBSF5GAAY+ibwpsEIPsxebq+VGo2BpCMrkjER+VNwP4kEO2yR4N3PRpWCYPdlo30LGsz73Pl0KGLF9owIpLwbaSwzygUHXFvGudgQ9xUpEWgkr/vH7YKT6xZUEhiHbPUCvyDSZ2fbaMN9nXSvdJ1M7x8VptpPif0po0uosIx5KCJiJWYP7RFiipaaw9ZaijlTMhnl5PCNUuQSQmVCz7phJMDj35sj+DFFaXAuK4Cpixa9l4ufrZYs6zstNpTz/ZUvTUa4=
    - secure: rPB5osWm2nLVhExdSIpE+ewmF8KSojHPWmmVLxEnnSYII7WdRt01G6lNvIZdhyAAI6JnZKZXvOKz8TghUwVf6fSgvm9VXC4jjXFVLaMW9uNeVeYi/pwSPRQQei1szpuGRBxi/ZwfJy9SkeEC6eMRthQinNtd2yKqbkLxo82QnPXo0NLRYBuPChMLpmwQe1in9MHsZtL/payfnmDXCd0POAtDULKSGBSgAQ8R5iYJ43NJ1NPeaS6evt7THOLtOntxXhDWPJL08g2Y3asLXxoHUc/fnqShXU/zGGt6oDDCzb4sg+OGtrHurEAKO7K3HmanDwEzRNiam98V7ADtyU81dY9ylVOJ3KGyLZIob/vIu0CMFR8cKvliyW11fC1CAHKwrFJ14ngkBKlSWXT48CrE0UkMaK7gZIdeoXMEr60mQU1spy+Yt5cafvlt0isgfka/JBcSYSVjrPVs620jQ+IFs6QReSoLyRsYTJ3PhcX3NxDEIELXhrwB2q1406BC+qrDxZX2oKYvqen6PR0p5s2EJGVrNwECjvT5TyYEcRKPm42kjC3KcsaBqexgkAdgYSGbNqie5I7OvCC/FNJc+KE3ZWhVPEtkc1hMJjYBtxgBL32sFkIT8H3jFaHCxmQD6XSPYoy1rqWzYjrsUeE23rUqfWjKMO6LrhURgemQbg8Ji4s=
# new MongoDB MONGO_LOGIN & MONGO_PASS
    - secure: UL5X6G4lepso9dFMrYit3iC55Hh10qO3El2cwzSvS3Iq1MwSZy5qHWuNFH8dEeK3gSazzeefoyum+nxaMrfhns8Wty+1pXQV7uWD0h+5GQTtinLOB0uqeQxk8iwMoUMStA574iGz+KCmppmj8yi1ZL+Ha86ncaEmrvRpfM2Khvn+nmc2cl+pC2n8nYW0OQuZog6v2Kfss87/11B6FUxuxWVWEW7DHHXNGGQH+0F7Eh/VsRHAXzmxIkfjX77/GMz1ac33xYxba7DjGu5deeljG9dOQlP+Et51cLkjeVcOZRpi5kAjiZ9H7t1KfpUt0EuYFPXjgIBDaEW9HJU16rwDE505g+Xp/f8jh9tx2k7K95w8BNJv+5QiGinMEU6d6A1YCgYiIBVsvxMDxrQvTw1ggOzAWG2iJawagJ9rB/Jkvj4WN0L1P4mT3/KvB8S87C/li450DgDkYTVW1R5oOAEuuJ0sbeAp+tMeKgT5ehyEy/VekFrppcNIo+uebXSlDgGKed39mZoioHPHiCKjWLKjUm47gB2IT38glY3jMi0IYjBkXyZIpWPMwWt/4bVrlDXxuCZSEqjOmCkJ7Ij27CFqRN8pvFDd6cfD9Tminrkj8KOQrVxCdhqq8s3e4PAf9bAHuZekkSVG74Yajwjo1ip+Ck5nMQffaYZeBN/GNSw5KO4=
    - secure: o38OCNYdT8/Ky+cowYHu7b5d+ZSzgx3HcT7hgBlhuXLwmD09uNpmYEo3K1jX24OcNli5krAmzQQDXZooVTXIBpidOnnXH7NSvU/KO/sTjRpy4NBGGfUd7zoTqTmj9lr+o1sTjHZCZIB9KVh7h4DbLUvSPUaer8tUvbQMaL2MnlXeMsOUKgbVEgf2Z3jrCNSoLoU6pQqWFJ8i003x8eREYUI/LY5Ea3ElNGM9Szcq8OlukRGrY1EwrVVvURq4/ahRM/K1HNxkjVzB8uGLQ8zMdNB8nPQWDY4pCBmVfWWV5rXiw34UJ6Gvr5IxAvNZPphQaqV6ogTwj6+ckhhP2NGzE9PTKFzrs7bCCFVZ3Iu63wZqNVZrhJgZUtdDKFUOt6DpG4HNS1vLaIIHuAdB7heb23iAohn8gPGOblowxhk6gwKHtD3GXewlAFiG+TO86wbh8/0Jjqb2H1MK5yi3QT4K9FCKxKA3WKuVllP9GKlqNd8U5Yudci1ErhhVL0nod8lxxmTq7O83XmGrL1vh+UkDLtJ5OH8C9UIswsIv6xEGqKp+yQXa7F0JU0uKdsCSgxZbDHLT+udbhlRwFaxYKg3IalWgVtqE5K5u6lg3nB9AutlUf+RiNYt/igPcW6SiA9GBirgF1+2PTA4LFPFAkL/kqgah7p3lLBbz/kupl7Qs1ws=